# config.yaml
global:
  model: "Qwen/Qwen2.5-3B-Instruct" 
  host: 127.0.0.1
  port: 8001       
  temperature: 0.0                        
  samples: 50                              # Number of query samples to test the agent on
  shuffle: true                             # Shuffle the test samples  
  save_trace: true     
  trace_path: "./trace.txt"                 # Path to save the traces                
  webshop_url: "http://143.215.138.94:3000"

agents:
  react_hotpotqa:
    type: "react"
    workload: "hotpotqa"
    iteration_limit: 20
    fewshot: 6
    shuffle: true

  react_webshop:
    type: "react"
    workload: "webshop"
    iteration_limit: 20
    fewshot: 2
    shuffle: true

  react_math:
    type: "react"
    workload: "math"
    iteration_limit: 20
    fewshot: 2
    shuffle: true
  
  react_humaneval:
    type: "react"
    workload: "humaneval"
    iteration_limit: 20
    fewshot: 1
    shuffle: true